# Generated by Django 3.0.4 on 2020-05-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
