# Generated by Django 3.0.4 on 2020-05-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sdes', '0002_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('K', models.IntegerField()),
                ('PT', models.IntegerField()),
                ('IP', models.IntegerField()),
                ('IPi', models.IntegerField()),
                ('P10', models.IntegerField()),
                ('P8', models.IntegerField()),
                ('P4', models.IntegerField()),
                ('E', models.IntegerField()),
                ('S0', models.IntegerField()),
                ('S1', models.IntegerField()),
                ('O', models.IntegerField()),
            ],
        ),
    ]
