# Generated by Django 3.0.4 on 2020-05-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdes', '0003_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='E',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='IP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='IPi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='O',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='P10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='P4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='P8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='S0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='S1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
