# Generated by Django 3.0.4 on 2020-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdes', '0004_auto_20200501_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='E',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='input',
            name='IP',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='input',
            name='IPi',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='input',
            name='O',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='input',
            name='P10',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='input',
            name='P4',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='input',
            name='P8',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='input',
            name='S0',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='input',
            name='S1',
            field=models.IntegerField(default=None),
        ),
    ]
