# Generated by Django 3.0.4 on 2020-05-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdes', '0006_auto_20200521_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='K',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
