# Generated by Django 3.0.4 on 2020-05-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdes', '0007_auto_20200521_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='K',
            field=models.CharField(max_length=200),
        ),
    ]
