# Generated by Django 3.0.4 on 2020-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdes', '0011_auto_20200521_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='P10',
            field=models.CharField(max_length=200),
        ),
    ]
