# Generated by Django 3.0.4 on 2020-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdes', '0012_auto_20200521_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='P10',
            field=models.IntegerField(default=None),
        ),
    ]
