# Generated by Django 3.0.4 on 2020-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdes', '0013_auto_20200521_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='P10',
            field=models.FloatField(default=None),
        ),
    ]
